services:
    OrderMediaConsoleApp:
        image: ordermedia/consoleapp:dev
        container_name: ordermedia.consoleapp.dev
        volumes:
          - /Users/pablo/Downloads/fotis/:/app/media
        environment:
          - MediaPaths__MediaSourcePath=/app/media
          - ClassificationFolders__ImageFolderName=img
          - ClassificationFolders__VideoFolderName=vid
          - MediaExtensions__ImageExtensions:0=.heic
          - MediaExtensions__ImageExtensions:1=.jpg
          - MediaExtensions__ImageExtensions:2=.jpeg
          - MediaExtensions__ImageExtensions:3=.gif
          - MediaExtensions__ImageExtensions:4=.png
          - MediaExtensions__ImageExtensions:5=.arw
          - MediaExtensions__ImageExtensions:6=.dng
          - MediaExtensions__ImageExtensions:7=.insp
          - MediaExtensions__ImageExtensions:8=.cr2
          - MediaExtensions__ImageExtensions:9=.cr3
          - MediaExtensions__VideoExtensions:0=.mov
          - MediaExtensions__VideoExtensions:1=.mp4
          - MediaExtensions__VideoExtensions:2=.insv
          - ClassificationSettings__OverwriteFiles=false
          - ClassificationSettings__RenameMediaFiles=true
          - ClassificationSettings__ReplaceLongNames=true
          - ClassificationSettings__MaxMediaNameLength=8
          - ClassificationSettings__NewMediaName=pbg
